# Generated by Django 3.1.7 on 2021-03-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_scorestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestat',
            name='score_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorestat',
            name='seven_days_score',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
