# Generated by Django 3.1.7 on 2021-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210315_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(blank=True, default='Work not Completed', max_length=300, null=True),
        ),
    ]
